version: "3.3"

services:
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      LANG: C.UTF-8
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - default

networks:
  default:
